### ISSUE TITLE
crash when fails to process icon

### ISSUE THREAD

**Issue by kupiqu** [ArturGaspar/kwin_auto_titlebar_colours#1]
```
Error processing icon help-browser
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "kwin_auto_titlebar_colours.py", line 179, in get_colours_for_icon
    for channel in ("Red", "Green", "Blue")))
  File "kwin_auto_titlebar_colours.py", line 179, in <genexpr>
    for channel in ("Red", "Green", "Blue")))
KeyError: 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kwin_auto_titlebar_colours.py", line 307, in update_application_colours
    icon_colours = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
KeyError: 0
```

Not sure I'm missing a dependency. I have python3-xdg and imagemagick installed in my system. Assuming there is nothing missing, this is then a bug. Ideally this would be fixed so all icons are properly processed. If this cannot be fixed for some reason, then the script should rather skip those and continue working.

**Comment by ArturGaspar** [comment]
Are you sure it is crashing and not just logging the exception and skipping the icon (as it should)?

https://github.com/ArturGaspar/kwin_auto_titlebar_colours/blob/20b2b21a539fff78dea9fc9c5a80b501e46a1f14/kwin_auto_titlebar_colours.py#L309

Do you see no new colour schemes in System Settings -> Colours or no new window rules?

**Comment by ArturGaspar** [comment]
Also can you please get the latest code and run it again? It should now log the icon path, then please send me that icon so I can check why it is happening.

**Comment by kupiqu** [comment]
I don't see new window rules.

I think the script is failing in all icons actually, there are tens if not hundreds of these errors, all related to /usr/share/icons/breeze-dark theme

EDIT: not all of them relate to breeze-dark, actually, I guess because some icons are inherited from other themes

**Comment by ArturGaspar** [comment]
Please upload just one of the failed icons.

What is your ImageMagick version (`convert --version`)?

**Comment by kupiqu** [comment]
```
convert --version
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib
```

**Comment by kupiqu** [comment]
for the case it is useful:

Operating System: KDE neon 5.17
KDE Plasma Version: 5.17.2
KDE Frameworks Version: 5.63.0
Qt Version: 5.13.1

**Comment by kupiqu** [comment]
Any icon, just an example:

Error processing icon: /usr/share/icons/breeze-dark/apps/48/kate.svg

I really don't think my KDE icons are any different than yours for the given version: 

KDE Applications Version: 19.08.3

In other words, the error must be elsewhere.

I have python3-xdg version 0.25.

**Comment by ArturGaspar** [comment]
Seems like a difference in ImageMagick output format. Should be fixed now. Can you please try again with the latest version?

**Comment by kupiqu** [comment]
I still got the following error, but it seems to work :)
```
convert-im6.q16: improper image header `/usr/share/icons/hicolor/64x64/apps/qview.png' @ error/png.c/ReadPNGImage/395
convert-im6.q16: no images defined `json:-' @ error/convert.c/ConvertImageCommand/3258.
Error processing icon: /usr/share/icons/hicolor/64x64/apps/qview.png
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "kwin_auto_titlebar_colours.py", line 185, in get_colours_for_icon
    data = json.loads(stdout)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kwin_auto_titlebar_colours.py", line 331, in update_application_colours
    icon_colours = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ArturGaspar** [comment]
Good. :) Thanks for the report.

**Comment by kupiqu** [comment]
Welcome and kudos, your script is amazing!

The error for the qview icon above is that there is something broken in it, it's not really an image :)
